name: STSEcon_RaidManager
main: cc.koffeecreations.RaidManager.Main
version: 2.0.0
api-version: 1.20
description: "Wintergrasped's Fully Custom Economy Plugins RaidManager"
authors: [Wintergrasped, TotallyNotLurkin]
depend: []
##loadbefore: [BKCommonLib, Train_Carts, CoreProtect]
commands:
   raidmanager:
      description: Raid Manager
      usage: /raidmanager